on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

name: badges

jobs:
  badges:
    uses: YiiRocks/.github/.github/workflows/badges.yml@main
    with:
      php-extensions: 'fileinfo, intl, pdo_sqlite'
